//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hospitalEntities : DbContext
    {
        public hospitalEntities()
            : base("name=hospitalEntities1")
        {
        }
        private static hospitalEntities _context;
        public static hospitalEntities Context
        {
            get
            {
                if (_context == null)
                    _context = new hospitalEntities();
                return _context;
            }
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cabinet> Cabinet { get; set; }
        public virtual DbSet<doctor> doctor { get; set; }
        public virtual DbSet<healingevent> healingevent { get; set; }
        public virtual DbSet<patient> patient { get; set; }
        public virtual DbSet<visit> visit { get; set; }
    }
}
