//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class doctor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public doctor()
        {
            this.healingevent = new HashSet<healingevent>();
            this.visit = new HashSet<visit>();


            this.photo = "Фото";
            this.name = "Имя";
            this.second_name = "Фамилия";
            this.father_name = "Отчество";
            this.passport = "123456789";
            this.birthday = DateTime.Now; // Default to current date/time
            this.sex = 0; // Default value for sex, you might want to use an enum for better clarity
            this.adress = "123 Колесникова";
            this.phone = "+375(29)000-00-00";
            this.specialization = "Специализация";
            this.post = "Врач";
            this.login = "username";
            this.password = "password";
        }


        public int id { get; set; }
        public string photo { get; set; }
        public string name { get; set; }
        public string second_name { get; set; }
        public string father_name { get; set; }
        public string passport { get; set; }
        public System.DateTime birthday { get; set; }
        public int sex { get; set; }
        public string adress { get; set; }
        public string phone { get; set; }
        public string specialization { get; set; }
        public string post { get; set; }
        public string login { get; set; }
        public string password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<healingevent> healingevent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<visit> visit { get; set; }
    }
}
