//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public patient()
        {
            this.healingevent = new HashSet<healingevent>();
            this.visit = new HashSet<visit>();
        }
    
        public int id { get; set; }
        public string photo { get; set; }
        public string name { get; set; }
        public string second_name { get; set; }
        public string father_name { get; set; }
        public string passport { get; set; }
        public System.DateTime birthday { get; set; }
        public int sex { get; set; }
        public string adress { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public int card_number { get; set; }
        public System.DateTime card_date { get; set; }
        public System.DateTime last_visit { get; set; }
        public System.DateTime next_visit { get; set; }
        public int policy_number { get; set; }
        public System.DateTime policy_end { get; set; }
        public string diagnosis { get; set; }
        public string history { get; set; }
        public string login { get; set; }
        public string password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<healingevent> healingevent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<visit> visit { get; set; }
    }
}
