//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class visit
    {
        public int id { get; set; }
        public int patient_id { get; set; }
        public int doctor_id { get; set; }
        public string type { get; set; }
        public System.DateTime date { get; set; }
        public string result { get; set; }
    
        public virtual doctor doctor { get; set; }
        public virtual patient patient { get; set; }
    }
}
